language:
    - python
python:
    - "2.6"
    - "2.7"
    - "pypy"
#    - "3.2"
#    - "3.3"
#    - "3.4"
#    - "pypy3"
#    - "nightly"
script:
    - "$TRAVIS_BUILD_DIR/build.sh"
    - "$TRAVIS_BUILD_DIR/test.sh"
after_success:
    - coveralls
