language:
    - python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy3"
    - "nightly"
script:
    - "$TRAVIS_BUILD_DIR/build.sh"
    - "$TRAVIS_BUILD_DIR/test.sh"
    - echo "$TRAVIS_PYTHON_VERSION"
    - if [ "$TRAVIS_PYTHON_VERSION" != "2.6" ] && [ "$TRAVIS_PYTHON_VERSION" != "3.2" ] && [ "$TRAVIS_PYTHON_VERSION" != "nightly" ]; then "$TRAVIS_BUILD_DIR/codeanalysis.sh"; fi
after_success:
    - coveralls
